import swaggerAutogen from 'swagger-autogen';

// Schemas generated by prisma and validators

import * as prismaSchemas from './json-schema.json';

const doc = {
  info: {
    title: 'REST Api Documentation',
    description: 'REST Api Documentation',
    version: '1.0.0'
  },
  components: {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    '@schemas': {
      ...prismaSchemas.definitions
    }
  },
  host: 'localhost:8000'
};

const outputFile = './openapi.json';
const routes = ['./src/app.ts'];

// Meant to be used with `npm run swagger`

void swaggerAutogen({ openapi: '3.0.0' })(outputFile, routes, doc);
