import swaggerAutogen from 'swagger-autogen';

// Schemas generated by prisma and validators

import { accountJsonSchemas } from '@shared/schemas';
import { authJsonSchemas } from '@shared/schemas';
import { channelJsonSchemas } from '@shared/schemas';
import { videosJsonSchemas } from '@shared/schemas';

const doc = {
  info: {
    title: 'REST Api Documentation',
    description: 'REST Api Documentation',
    version: '1.0.0'
  },
  components: {
    '@schemas': {
      ...accountJsonSchemas,
      ...authJsonSchemas,
      ...channelJsonSchemas,
      ...videosJsonSchemas
    },
    securitySchemes: {
      SessionAuth: {
        type: 'apiKey',
        name: 'sessionId',
        in: 'cookie'
      }
    }
  },
  host: 'localhost:8000'
};

const outputFile = './openapi.json';
const routes = ['./src/app.ts'];

// Meant to be used with `npm run swagger`

void swaggerAutogen({ openapi: '3.0.0' })(outputFile, routes, doc);
